GET http://localhost:3000/syc/users

###

GET http://localhost:3000/syc/users/68263e4fea86a5e3e602f793

###

POST http://localhost:3000/syc/users
Content-type: application/json

{
  "name": "Jonah Goldberg",
  "emailAddress": "jonah@example.com"
}

###

PATCH http://localhost:3000/syc/users/68263e4fea86a5e3e602f793
Content-type: application/json

{
  "name": "Mary Ann Collins",
  "emailAddress":"maryann@example.com"
}

###

DELETE http://localhost:3000/syc/users/682643dcf37d6f138c88de50


###

GET http://localhost:3000/syc/closetitems

###

GET http://localhost:3000/syc/closetitems/6827780181eef913a1e6f182

###

POST http://localhost:3000/syc/closetitems
Content-type: application/json

{
  "category": "Footwear",
  "name": "Tevas",
  "season": "Summer",
  "size": "8",
  "desc": "You know, kind of rough.",
  "rating": "6.8"
}
