GET http://localhost:3000/syc/users

###

GET http://localhost:3000/syc/users/68263e25ea86a5e3e602f792

###

POST http://localhost:3000/syc/users
Content-type: application/json

{
  "name": "Sarah Lyons",
  "emailAddress": "sarah@example.com"
}

###

DELETE http://localhost:3000/syc/users/682643dcf37d6f138c88de50


###

GET http://localhost:3000/syc/closetitems

###

GET http://localhost:3000/syc/closetitems/6827793881eef913a1e6f18a
